### ISSUE TITLE
Allow accessing add-on attributes in photo-z composite catalogs 

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#475]
Some of the photo-z composite catalog configs have the line
```yaml
only_use_master_attr: true
```
However, sometimes it is desirable to access attributes in the add-on catalogs, not just the ones in the main catalog. In those case, this option should be removed from the config files. See e.g., https://github.com/LSSTDESC/DC2-analysis/pull/145#discussion_r456829248.  

@sschmidt23 can you remove this line when appropriate?

**Comment by yymao** [comment]
I think this has been fixed. @sschmidt23 if it's not the case please reopen.

**Comment by sschmidt23** [comment]
I just checked, there are two files that still have this issue (and one with an unnecessary only_use_master_attr: False), making a PR to fix this now.
